// Self-hosts the two web fonts. Google Fonts would log every EU visitor's IP with a
// third party, so we fetch its CSS once, keep the same @font-face rules and serve the
// woff2 files from /assets/fonts/. Re-run only to pick up a new upstream font version.
import { mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs';

const CSS_URL = 'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Nunito:wght@700;800;900&display=swap';
// Google picks the format by User-Agent; a current Chrome gets woff2 split by unicode-range.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';
const OUT = 'assets/fonts';
const FAMILIES = new Set(['DM Sans', 'Nunito']);

const die = (msg) => { console.error(`build_fonts: ${msg}`); process.exit(1); };

async function get(url) {
  const res = await fetch(url, { redirect: 'error', headers: { 'user-agent': UA } });
  if (!res.ok) die(`${url} answered ${res.status}`);
  return res;
}

const css = await (await get(CSS_URL)).text();
const BLOCK = /\/\* ([a-z-]+) \*\/\s*@font-face \{([^}]*)\}/g;
const FILE = /^https:\/\/fonts\.gstatic\.com\/s\/([a-z0-9]+)\/(v\d+)\/[A-Za-z0-9_-]+\.woff2$/;
const faces = [...css.matchAll(BLOCK)].map(([, subset, body]) => {
  const prop = (name, re) => {
    const m = body.match(new RegExp(`\\n\\s*${name}: (${re.source});\\n`));
    if (!m) die(`${subset} face has no valid ${name}`);
    return m[1];
  };
  const family = prop('font-family', /'[^']+'/).slice(1, -1);
  const url = prop('src', /url\([^)]+\) format\('woff2'\)/).match(/^url\(([^)]+)\)/)[1];
  if (!FAMILIES.has(family)) die(`unexpected family ${family}`);
  if (!FILE.test(url)) die(`unexpected font URL ${url}`);
  return {
    subset, family, url,
    style: prop('font-style', /normal|italic/),
    weight: prop('font-weight', /\d{3}/),
    display: prop('font-display', /swap/),
    range: prop('unicode-range', /U\+[0-9A-F?]+(?:-[0-9A-F]+)?(?:, U\+[0-9A-F?]+(?:-[0-9A-F]+)?)*/)
  };
});
if (!faces.length || faces.length !== (css.match(/@font-face/g) || []).length) die('could not parse every @font-face block');
if (!faces.some((f) => f.subset === 'cyrillic')) die('no cyrillic subset, the Russian pages need one');

// Variable fonts reuse one file for every weight; only split names if a weight gets its own file.
const byKey = new Map();
for (const f of faces) {
  const [, slug, ver] = f.url.match(FILE);
  f.key = `${slug}-${ver}-${f.subset}`;
  byKey.set(f.key, (byKey.get(f.key) || new Set()).add(f.url));
}
const local = new Map();
for (const f of faces) local.set(f.url, byKey.get(f.key).size > 1 ? `${f.key}-${f.weight}.woff2` : `${f.key}.woff2`);

mkdirSync(OUT, { recursive: true });
let total = 0;
for (const [url, name] of local) {
  const bytes = Buffer.from(await (await get(url)).arrayBuffer());
  if (bytes.subarray(0, 4).toString('latin1') !== 'wOF2') die(`${url} is not a woff2 file`);
  writeFileSync(`${OUT}/${name}`, bytes);
  total += bytes.length;
  console.log(`${name.padEnd(34)} ${(bytes.length / 1024).toFixed(1).padStart(6)} KB`);
}

const rules = faces.map((f) => `/* ${f.subset} */
@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: ${f.display};
  src: url(${local.get(f.url)}) format('woff2');
  unicode-range: ${f.range};
}`).join('\n');
writeFileSync(`${OUT}/fonts.css`, `/* generated by tools/build_fonts.mjs from Google Fonts: DM Sans and Nunito, SIL Open Font License 1.1 */\n${rules}\n`);

const stale = readdirSync(OUT).filter((n) => n.endsWith('.woff2') && ![...local.values()].includes(n));
if (stale.length) console.log(`no longer referenced, delete by hand: ${stale.join(', ')}`);
console.log(`${OUT}/fonts.css: ${faces.length} faces, ${local.size} files, ${(total / 1024).toFixed(1)} KB of woff2 (${statSync(`${OUT}/fonts.css`).size} B css)`);
console.log('subsets:', [...FAMILIES].map((fam) => `${fam}: ${[...new Set(faces.filter((f) => f.family === fam).map((f) => f.subset))].join(', ')}`).join(' | '));
