// Questions written for the website only. Deliberately NOT the app's 800-card deck:
// the site can be scraped, the app's content should stay the reason to install.
export const WEB_DECK = {
  never_have_i: {
    slug: { en: 'play/never-have-i-ever', ru: 'ru/play/ya-nikogda-ne' },
    en: [
      'Never have I ever answered a text three weeks late and opened with "sorry, just saw this"',
      'Never have I ever pretended to know a song and mumbled the whole chorus',
      'Never have I ever left a group chat and immediately regretted it',
      'Never have I ever taken a longer route home just to finish a podcast',
      'Never have I ever agreed to plans I was already planning to cancel',
      'Never have I ever rehearsed a phone call before making it',
      'Never have I ever kept a receipt for something I fully intended to return and never did',
      'Never have I ever laughed at a joke I did not hear at all',
      'Never have I ever rewritten a one-line message four times',
      'Never have I ever claimed the last slice was fine to take because nobody said anything',
      'Never have I ever hidden from a neighbour in my own hallway',
      'Never have I ever bought something because the queue for it was long',
      'Never have I ever said "I am five minutes away" from my bed',
      'Never have I ever kept a plant alive purely out of spite',
      'Never have I ever practised an argument in the shower and won it dramatically',
      'Never have I ever taken a photo of a menu and never looked at it again',
      'Never have I ever called someone by the wrong name for months',
      'Never have I ever moved a meeting so I could keep watching something',
      'Never have I ever pretended my phone died to end a conversation',
      'Never have I ever kept a gift I disliked because throwing it out felt rude',
      'Never have I ever gone to a shop for one thing and left with nine',
      'Never have I ever nodded through directions I did not understand',
      'Never have I ever told a story as mine when it happened to a friend',
      'Never have I ever stayed at a party only because leaving felt awkward'
    ],
    ru: [
      'Я никогда не отвечал на сообщение через три недели со слов «прости, только увидел»',
      'Я никогда не делал вид, что знаю песню, и мычал весь припев',
      'Я никогда не выходил из беседы и через минуту не жалел об этом',
      'Я никогда не шёл домой длинной дорогой, чтобы досмотреть подкаст',
      'Я никогда не соглашался на планы, которые уже собирался отменить',
      'Я никогда не репетировал звонок перед тем, как позвонить',
      'Я никогда не хранил чек от вещи, которую твёрдо собирался вернуть, и не возвращал',
      'Я никогда не смеялся над шуткой, которую вообще не услышал',
      'Я никогда не переписывал сообщение из одной строки четыре раза',
      'Я никогда не забирал последний кусок, потому что никто не возразил',
      'Я никогда не прятался от соседа в собственном подъезде',
      'Я никогда не покупал что-то только потому, что за этим стояла очередь',
      'Я никогда не говорил «я в пяти минутах», лежа в кровати',
      'Я никогда не держал растение живым из чистого упрямства',
      'Я никогда не отрабатывал спор в душе и не побеждал в нём красиво',
      'Я никогда не фотографировал меню и не открывал этот снимок больше никогда',
      'Я никогда не называл человека чужим именем месяцами',
      'Я никогда не переносил встречу, чтобы досмотреть серию',
      'Я никогда не говорил, что телефон сел, чтобы закончить разговор',
      'Я никогда не оставлял подарок, который не понравился, просто потому что выбросить неловко',
      'Я никогда не заходил в магазин за одним и не выходил с девятью',
      'Я никогда не кивал в ответ на объяснение дороги, которое не понял',
      'Я никогда не рассказывал как свою историю, которая случилась с другом',
      'Я никогда не оставался на вечеринке только потому, что уйти было неловко'
    ]
  },
  roulette: {
    slug: { en: 'play/who-knows-better', ru: 'ru/play/kto-iz-nas' },
    names: { en: ['Alex', 'Sam'], ru: ['Аня', 'Макс'] },
    en: [
      '{A}, what did you think of {B} the first five minutes you met?',
      '{A}, which of {B}\u2019s habits would you steal if you could?',
      '{A}, when did {B} last talk you out of a bad idea?',
      '{A}, what would {B} never admit out loud but everyone knows?',
      '{A}, what is the worst advice {B} ever gave you?',
      '{A}, where would you take {B} with no budget limit?',
      '{A}, what does {B} do that makes a room easier to be in?',
      '{A}, which story about {B} do you retell most often?',
      '{A}, what would {B} be doing in ten years if nothing stopped them?',
      '{A}, when did you last see {B} genuinely proud of something?',
      '{A}, what is the smallest favour from {B} you still remember?',
      '{A}, what would {B} pick as their last meal?',
      '{A}, what do you and {B} argue about every single time?',
      '{A}, which of your traits did {B} rub off on you?',
      '{A}, what did you get wrong about {B} at first?',
      '{A}, what would {B} do with a completely free week?',
      '{A}, when did {B} surprise you most recently?',
      '{A}, what task would you trust only {B} with?',
      '{A}, what does {B} take far more seriously than anyone expects?',
      '{A}, what would you thank {B} for if it were not awkward?',
      '{A}, which decision of {B}\u2019s do you quietly admire?',
      '{A}, what is {B} unreasonably good at?',
      '{A}, what would {B} say your worst habit is?',
      '{A}, what do you hope {B} never changes?'
    ],
    ru: [
      '*Аня*, что ты подумала о *Максе* в первые пять минут знакомства?',
      '*Аня*, какую привычку *Макса* ты бы себе забрала?',
      '*Аня*, когда *Макс* последний раз отговорил тебя от плохой идеи?',
      '*Аня*, в чём *Макс* никогда не признается вслух, хотя все знают?',
      '*Аня*, какой самый плохой совет ты слышала от *Макса*?',
      '*Аня*, куда бы ты повезла *Макса*, если бы деньги не считались?',
      '*Аня*, что делает *Макс* такого, от чего в компании становится легче?',
      '*Аня*, какую историю про *Макса* ты пересказываешь чаще всего?',
      '*Аня*, чем бы *Макс* занимался через десять лет, если бы ничто не мешало?',
      '*Аня*, когда ты последний раз видела *Макса* по-настоящему довольным собой?',
      '*Аня*, какую мелкую услугу от *Макса* ты до сих пор помнишь?',
      '*Аня*, что *Макс* выбрал бы последним блюдом в жизни?',
      '*Аня*, о чём вы с *Максом* спорите каждый раз?',
      '*Аня*, какая твоя черта появилась из-за *Макса*?',
      '*Аня*, в чём ты ошибалась насчёт *Макса* поначалу?',
      '*Аня*, чем бы *Макс* занялся, будь у него совершенно свободная неделя?',
      '*Аня*, чем *Макс* удивил тебя в последнее время?',
      '*Аня*, какое дело ты доверила бы только *Максу*?',
      '*Аня*, к чему *Макс* относится гораздо серьёзнее, чем кажется?',
      '*Аня*, за что бы ты поблагодарила *Макса*, если бы это не было неловко?',
      '*Аня*, какое решение *Макса* ты тихо уважаешь?',
      '*Аня*, в чём *Макс* неприлично хорош?',
      '*Аня*, что *Макс* назвал бы твоей худшей привычкой?',
      '*Аня*, что в *Максе* ты не хочешь, чтобы менялось?'
    ]
  },
  tell_a_moment: {
    slug: { en: 'play/questions-to-ask-friends', ru: 'ru/play/voprosy-druzyam' },
    en: [
      'Tell us about a day that turned out completely different from the plan',
      'Tell us about the last time you were proud of yourself and told nobody',
      'Tell us about a stranger you still think about',
      'Tell us about the best thing you ever bought for under ten euros',
      'Tell us about a moment you knew a friendship would last',
      'Tell us about a place you would go back to tomorrow',
      'Tell us about the worst haircut of your life',
      'Tell us about a time you were completely, confidently wrong',
      'Tell us about a compliment you have never forgotten',
      'Tell us about the first thing you ever saved money for',
      'Tell us about a rule at home you only understood as an adult',
      'Tell us about a trip that went wrong in a way you now love',
      'Tell us about a song that instantly puts you somewhere else',
      'Tell us about the smartest thing a child has said to you',
      'Tell us about a night you did not want to end',
      'Tell us about something you quit and never regretted',
      'Tell us about the last time you laughed until it hurt',
      'Tell us about a skill you picked up for a stupid reason',
      'Tell us about a message you were terrified to send',
      'Tell us about the kindest thing a stranger did for you',
      'Tell us about a habit you copied from someone you love',
      'Tell us about the moment you felt like an adult for the first time',
      'Tell us about a fear you grew out of',
      'Tell us about a photo of yourself you would never delete'
    ],
    ru: [
      'Расскажи про день, который пошёл совсем не по плану',
      'Расскажи, когда ты в последний раз собой гордился и никому не сказал',
      'Расскажи про незнакомого человека, о котором до сих пор думаешь',
      'Расскажи про лучшую вещь, купленную дешевле десяти евро',
      'Расскажи про момент, когда понял, что эта дружба надолго',
      'Расскажи про место, куда вернулся бы хоть завтра',
      'Расскажи про худшую стрижку в своей жизни',
      'Расскажи, когда ты был совершенно уверен и совершенно неправ',
      'Расскажи про комплимент, который не забываешь',
      'Расскажи, на что ты первый раз в жизни копил',
      'Расскажи про домашнее правило, которое понял только взрослым',
      'Расскажи про поездку, которая сорвалась так, что теперь вспоминаешь с любовью',
      'Расскажи про песню, которая мгновенно переносит в другое место',
      'Расскажи самую умную фразу, которую слышал от ребёнка',
      'Расскажи про вечер, который не хотелось заканчивать',
      'Расскажи, что ты бросил и ни разу не пожалел',
      'Расскажи, когда ты последний раз смеялся до боли в животе',
      'Расскажи про навык, которому научился по глупой причине',
      'Расскажи про сообщение, которое было страшно отправить',
      'Расскажи, что самое доброе сделал для тебя незнакомый человек',
      'Расскажи про привычку, которую перенял у близкого человека',
      'Расскажи, когда впервые почувствовал себя взрослым',
      'Расскажи про страх, который ты перерос',
      'Расскажи про свою фотографию, которую никогда не удалишь'
    ]
  },
  would_you_rather: {
    slug: { en: 'play/would-you-rather', ru: 'ru/play/chto-vyberesh' },
    en: [
      'Would you rather always be twenty minutes early or ten minutes late?',
      'Would you rather lose the ability to lie or the ability to keep a secret?',
      'Would you rather have unlimited free flights or unlimited free food?',
      'Would you rather work four long days or six short ones?',
      'Would you rather know how you die or when you die?',
      'Would you rather never wait in a queue or never sit in traffic?',
      'Would you rather read minds for a day or be invisible for a week?',
      'Would you rather live without music or without films?',
      'Would you rather always say what you think or never speak first?',
      'Would you rather have a photographic memory or perfect intuition?',
      'Would you rather lose every photo you have or every message you have sent?',
      'Would you rather be famous for something small or respected by five people?',
      'Would you rather sleep four hours and feel fine or ten hours and feel slow?',
      'Would you rather redo one year of your life or skip one year ahead?',
      'Would you rather never feel cold or never feel tired?',
      'Would you rather be the funniest person in the room or the calmest?',
      'Would you rather always travel alone or never travel alone?',
      'Would you rather win an argument or keep the peace?',
      'Would you rather have one perfect friend or ten good ones?',
      'Would you rather eat the same breakfast forever or never eat breakfast?',
      'Would you rather lose your sense of smell or your sense of direction?',
      'Would you rather be underestimated or overestimated?',
      'Would you rather live in a city that never sleeps or a village that never changes?',
      'Would you rather know every language or play every instrument?'
    ],
    ru: [
      'Что выберешь: всегда приходить на двадцать минут раньше или опаздывать на десять?',
      'Что выберешь: потерять умение врать или умение хранить секреты?',
      'Что выберешь: бесплатные перелёты навсегда или бесплатную еду навсегда?',
      'Что выберешь: четыре длинных рабочих дня или шесть коротких?',
      'Что выберешь: знать, как ты умрёшь, или когда?',
      'Что выберешь: никогда не стоять в очереди или никогда не стоять в пробке?',
      'Что выберешь: читать мысли один день или быть невидимым неделю?',
      'Что выберешь: жить без музыки или без кино?',
      'Что выберешь: всегда говорить, что думаешь, или никогда не начинать разговор?',
      'Что выберешь: идеальную память или идеальную интуицию?',
      'Что выберешь: потерять все свои фотографии или все отправленные сообщения?',
      'Что выберешь: известность за пустяк или уважение пяти человек?',
      'Что выберешь: спать четыре часа и быть бодрым или десять и быть вялым?',
      'Что выберешь: переиграть один год жизни или перепрыгнуть год вперёд?',
      'Что выберешь: никогда не мёрзнуть или никогда не уставать?',
      'Что выберешь: быть самым смешным в компании или самым спокойным?',
      'Что выберешь: всегда путешествовать один или никогда не путешествовать один?',
      'Что выберешь: победить в споре или сохранить мир?',
      'Что выберешь: одного идеального друга или десять хороших?',
      'Что выберешь: один и тот же завтрак всю жизнь или совсем без завтрака?',
      'Что выберешь: лишиться обоняния или чувства направления?',
      'Что выберешь: чтобы тебя недооценивали или переоценивали?',
      'Что выберешь: город, который никогда не спит, или деревню, которая не меняется?',
      'Что выберешь: знать все языки или играть на всех инструментах?'
    ]
  }
};

export const DECK_LIMIT = 8;   // cards per day on the web; the rest lives in the app
